/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiUploadsPresignedUrlRouteImport } from './routes/api/uploads/presigned-url'
import { Route as ApiUploadsCompleteRouteImport } from './routes/api/uploads/complete'
import { Route as ApiBillingSubscriptionRouteImport } from './routes/api/billing/subscription'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedBillingSuccessRouteImport } from './routes/_protected/billing.success'
import { Route as ApiUploadsIdIndexRouteImport } from './routes/api/uploads/$id/index'
import { Route as ApiUploadsIdViewRouteImport } from './routes/api/uploads/$id/view'
import { Route as ApiUploadsIdDownloadRouteImport } from './routes/api/uploads/$id/download'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsPresignedUrlRoute = ApiUploadsPresignedUrlRouteImport.update({
  id: '/api/uploads/presigned-url',
  path: '/api/uploads/presigned-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsCompleteRoute = ApiUploadsCompleteRouteImport.update({
  id: '/api/uploads/complete',
  path: '/api/uploads/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSubscriptionRoute = ApiBillingSubscriptionRouteImport.update({
  id: '/api/billing/subscription',
  path: '/api/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBillingSuccessRoute = ProtectedBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ProtectedBillingRoute,
} as any)
const ApiUploadsIdIndexRoute = ApiUploadsIdIndexRouteImport.update({
  id: '/api/uploads/$id/',
  path: '/api/uploads/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdViewRoute = ApiUploadsIdViewRouteImport.update({
  id: '/api/uploads/$id/view',
  path: '/api/uploads/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdDownloadRoute = ApiUploadsIdDownloadRouteImport.update({
  id: '/api/uploads/$id/download',
  path: '/api/uploads/$id/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/billing': typeof ProtectedBillingRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/user': typeof ApiUserRoute
  '/billing/success': typeof ProtectedBillingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/uploads/complete': typeof ApiUploadsCompleteRoute
  '/api/uploads/presigned-url': typeof ApiUploadsPresignedUrlRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/api/uploads/$id/download': typeof ApiUploadsIdDownloadRoute
  '/api/uploads/$id/view': typeof ApiUploadsIdViewRoute
  '/api/uploads/$id': typeof ApiUploadsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/billing': typeof ProtectedBillingRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/user': typeof ApiUserRoute
  '/billing/success': typeof ProtectedBillingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/uploads/complete': typeof ApiUploadsCompleteRoute
  '/api/uploads/presigned-url': typeof ApiUploadsPresignedUrlRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/api/uploads/$id/download': typeof ApiUploadsIdDownloadRoute
  '/api/uploads/$id/view': typeof ApiUploadsIdViewRoute
  '/api/uploads/$id': typeof ApiUploadsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/_protected/billing': typeof ProtectedBillingRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/user': typeof ApiUserRoute
  '/_protected/billing/success': typeof ProtectedBillingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/uploads/complete': typeof ApiUploadsCompleteRoute
  '/api/uploads/presigned-url': typeof ApiUploadsPresignedUrlRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/uploads/$id/download': typeof ApiUploadsIdDownloadRoute
  '/api/uploads/$id/view': typeof ApiUploadsIdViewRoute
  '/api/uploads/$id/': typeof ApiUploadsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dpa'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/billing'
    | '/dashboard'
    | '/api/user'
    | '/billing/success'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/subscription'
    | '/api/uploads/complete'
    | '/api/uploads/presigned-url'
    | '/api/webhooks/polar'
    | '/api/uploads'
    | '/api/uploads/$id/download'
    | '/api/uploads/$id/view'
    | '/api/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dpa'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/billing'
    | '/dashboard'
    | '/api/user'
    | '/billing/success'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/subscription'
    | '/api/uploads/complete'
    | '/api/uploads/presigned-url'
    | '/api/webhooks/polar'
    | '/api/uploads'
    | '/api/uploads/$id/download'
    | '/api/uploads/$id/view'
    | '/api/uploads/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/dpa'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/api/user'
    | '/_protected/billing/success'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/subscription'
    | '/api/uploads/complete'
    | '/api/uploads/presigned-url'
    | '/api/webhooks/polar'
    | '/api/uploads/'
    | '/api/uploads/$id/download'
    | '/api/uploads/$id/view'
    | '/api/uploads/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DpaRoute: typeof DpaRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingSubscriptionRoute: typeof ApiBillingSubscriptionRoute
  ApiUploadsCompleteRoute: typeof ApiUploadsCompleteRoute
  ApiUploadsPresignedUrlRoute: typeof ApiUploadsPresignedUrlRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
  ApiUploadsIdDownloadRoute: typeof ApiUploadsIdDownloadRoute
  ApiUploadsIdViewRoute: typeof ApiUploadsIdViewRoute
  ApiUploadsIdIndexRoute: typeof ApiUploadsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/presigned-url': {
      id: '/api/uploads/presigned-url'
      path: '/api/uploads/presigned-url'
      fullPath: '/api/uploads/presigned-url'
      preLoaderRoute: typeof ApiUploadsPresignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/complete': {
      id: '/api/uploads/complete'
      path: '/api/uploads/complete'
      fullPath: '/api/uploads/complete'
      preLoaderRoute: typeof ApiUploadsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscription': {
      id: '/api/billing/subscription'
      path: '/api/billing/subscription'
      fullPath: '/api/billing/subscription'
      preLoaderRoute: typeof ApiBillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/billing/success': {
      id: '/_protected/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof ProtectedBillingSuccessRouteImport
      parentRoute: typeof ProtectedBillingRoute
    }
    '/api/uploads/$id/': {
      id: '/api/uploads/$id/'
      path: '/api/uploads/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id/view': {
      id: '/api/uploads/$id/view'
      path: '/api/uploads/$id/view'
      fullPath: '/api/uploads/$id/view'
      preLoaderRoute: typeof ApiUploadsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id/download': {
      id: '/api/uploads/$id/download'
      path: '/api/uploads/$id/download'
      fullPath: '/api/uploads/$id/download'
      preLoaderRoute: typeof ApiUploadsIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedBillingRouteChildren {
  ProtectedBillingSuccessRoute: typeof ProtectedBillingSuccessRoute
}

const ProtectedBillingRouteChildren: ProtectedBillingRouteChildren = {
  ProtectedBillingSuccessRoute: ProtectedBillingSuccessRoute,
}

const ProtectedBillingRouteWithChildren =
  ProtectedBillingRoute._addFileChildren(ProtectedBillingRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBillingRoute: typeof ProtectedBillingRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBillingRoute: ProtectedBillingRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DpaRoute: DpaRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ApiUserRoute: ApiUserRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingSubscriptionRoute: ApiBillingSubscriptionRoute,
  ApiUploadsCompleteRoute: ApiUploadsCompleteRoute,
  ApiUploadsPresignedUrlRoute: ApiUploadsPresignedUrlRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
  ApiUploadsIdDownloadRoute: ApiUploadsIdDownloadRoute,
  ApiUploadsIdViewRoute: ApiUploadsIdViewRoute,
  ApiUploadsIdIndexRoute: ApiUploadsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
